version: '2'

networks:
  back-tier:
    driver: bridge

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGODB_ROOT_PASSWORD: password
    networks:
      - back-tier
  redis:
    build: ./composeFiles/redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - data:/var/lib/redis
    networks:
      - back-tier

  data:
    image: ubuntu
    container_name: data

  rabbitmq:
    build: ./composeFiles/rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - back-tier

  elk:
    image: sebp/elk
    container_name: elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
      - "5000:5000"
    networks:
      - back-tier

  php:
    build: ./composeFiles/php
    container_name: php
    volumes:
      - ${PWD}/src:/var/www/html
    ports:
      - "80:80"

    networks:
      - back-tier

volumes:
  data:
    driver: local
