mongo:
  image: mongo
  container_name: mongo
  ports:
    - "27017:27017"
  environment:
    MONGODB_ROOT_PASSWORD: password
# redis:
#   build: ./composeFiles/redis
#   container_name: redis
#   ports:
#     - "6379:6379"
php:
 build: ./composeFiles/php
 container_name: php
 volumes:
     - ${PWD}/src:/var/www/html
 ports:
    - "80:80"
 links:
   - mongo:mongo
# apache:
#  build: ./composeFiles/apache
#  container_name: apache
#  ports:
#   - "80:80"
#  links:
#   - php:php
 #  - ${PWD}/logs/php7:/var/log:rw

#

# web:
#   image: teseo/nginx
#   container_name: web
#   ports:
#     - "80:80"
#     - "443:443"
#   links:
#     - php7:php7
#   volumes:
#     - ${PWD}/app:/var/www
#     - ./sites:/etc/nginx/conf.d
#   #  - ${PWD}/logs/nginx:/var/log:rw
#
# #
# # search:
# #   image: elasticsearch
# #   container_name: search
# #   ports:
# #     - "9200:9200"
# #     - "9300:9300"
